# Generated by Django 5.2.4 on 2025-07-31 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_products_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Products",
        ),
    ]
