# Generated by Django 5.2.4 on 2025-07-31 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_product_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
