# Generated by Django 5.2.4 on 2025-07-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_rename_products_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("text", models.TextField(blank=True)),
            ],
        ),
    ]
